apiVersion: batch/v1
kind: CronJob
metadata:
  name: ejemplo-cronjob-node
spec:
  schedule: "*/3 * * * *"   # Cada 5 minutos
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: node-cronjob
              image: danielink28/joyeria:2.0